name: Build and test package
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '12.4' }}
      XC_PROJ: ${{ 'Nog.xcodeproj' }}
      XC_SCHEME: ${{ 'NogTests' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Run tests
      run: /usr/bin/xcodebuild test -project "$XC_PROJ" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 12'